name: CI / CD

on:
  push:
    branches:
      - "master"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3

        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5

        with:
          context: .
          push: true
          tags: ruanwill/code-delivery-app:${{github.run_number}}

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Azure Login
        uses: Azure/login@v2.0.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Azure Container Apps Build and Deploy
        uses: Azure/container-apps-deploy-action@v2

        with:
          imageToDeploy: ruanwill/code-delivery-api:${{github.run_number}}
          containerAppName: app-delivery-front
          resourceGroup: app-delivery
